/**
 * User API
 * This is an API for managing users.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@spiderman.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * new user form data
 */
export interface ModelsUserCreationForm { 
    department?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    userName?: string;
}