/**
 * User API
 * This is an API for managing users.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@spiderman.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ModelsUserStatus = 'I' | 'A' | 'T';

export const ModelsUserStatus = {
    I: 'I' as ModelsUserStatus,
    A: 'A' as ModelsUserStatus,
    T: 'T' as ModelsUserStatus
};